<!DOCTYPE html><html lang="en-gb" >

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.8.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Ernest Guevarra">

  
  
  
    
  
  <meta name="description" content="In this blog post, we explore the use of **sentiment analysis** to assess emotional intent of words within the IATF resolutions. This is in line with our project on the use of text analysis and topic modelling techniques for analysis of policies regarding the COVID-19 pandemic in the Philippines.">

  
  <link rel="alternate" hreflang="en-gb" href="/post/applying-sentiment-analysis/">

  


  
  
  
  <meta name="theme-color" content="#3f51b5">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha256-4w9DunooKSr3MFXHXWyFER38WmPdm361bQS/2KUWZbU=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css" integrity="sha256-SHMGCYmST46SoyGgo4YR/9AlK1vf3ff84Aq9yK4hdqM=" crossorigin="anonymous">
    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  




  


  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_hu2841c55c99b54125efcb63e118ead72c_103426_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hu2841c55c99b54125efcb63e118ead72c_103426_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="/post/applying-sentiment-analysis/">

  
  
  
  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="og:site_name" content="CoMo Philippines">
  <meta property="og:url" content="/post/applying-sentiment-analysis/">
  <meta property="og:title" content="Applying sentiment analysis on IATF resolutions | CoMo Philippines">
  <meta property="og:description" content="In this blog post, we explore the use of **sentiment analysis** to assess emotional intent of words within the IATF resolutions. This is in line with our project on the use of text analysis and topic modelling techniques for analysis of policies regarding the COVID-19 pandemic in the Philippines."><meta property="og:image" content="/post/applying-sentiment-analysis/featured.png">
  <meta property="twitter:image" content="/post/applying-sentiment-analysis/featured.png"><meta property="og:locale" content="en-gb">
  
    
      <meta property="article:published_time" content="2020-05-26T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2020-06-18T00:00:00&#43;00:00">
  

  


    






  




<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "/post/applying-sentiment-analysis/"
  },
  "headline": "Applying sentiment analysis on IATF resolutions",
  
  "image": [
    "/post/applying-sentiment-analysis/featured.png"
  ],
  
  "datePublished": "2020-05-26T00:00:00Z",
  "dateModified": "2020-06-18T00:00:00Z",
  
  "author": {
    "@type": "Person",
    "name": "Ernest Guevarra"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "CoMo Philippines",
    "logo": {
      "@type": "ImageObject",
      "url": "/images/icon_hu2841c55c99b54125efcb63e118ead72c_103426_192x192_fill_lanczos_center_2.png"
    }
  },
  "description": "In this blog post, we explore the use of **sentiment analysis** to assess emotional intent of words within the IATF resolutions. This is in line with our project on the use of text analysis and topic modelling techniques for analysis of policies regarding the COVID-19 pandemic in the Philippines."
}
</script>

  

  


  
  
  
  
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.1/cookieconsent.min.js" integrity="sha256-5VhCqFam2Cn+yjw61zbBNrbHVJ6SRydPeKopYlngbiQ=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.1/cookieconsent.min.css" integrity="sha256-zQ0LblD/Af8vOppw18+2anxsuaz3pWYyVWi+bTvTH8Q=" crossorigin="anonymous">
  
  <script>
  window.addEventListener("load", function(){
    window.cookieconsent.initialise({
      "palette": {
        "popup": {
          "background": "#3f51b5",
          "text": "#fff"
        },
        "button": {
          "background": "#fff",
          "text": "#3f51b5"
        }
      },
      "theme": "classic",
      "content": {
        "message": "This website uses cookies to ensure you get the best experience on our website.",
        "dismiss": "Got it!",
        "link": "Learn more",
        "href": "/privacy/"
      }
    })});
  </script>



  





  <title>Applying sentiment analysis on IATF resolutions | CoMo Philippines</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  







<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">CoMo Philippines</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">CoMo Philippines</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-end" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/#"><span>Home</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#projects"><span>Projects</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#" aria-label="Search"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      <li class="nav-item dropdown theme-dropdown">
        <a href="#" class="nav-link js-theme-selector" data-toggle="dropdown" aria-haspopup="true">
          <i class="fas fa-palette" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu">
          <a href="#" class="dropdown-item js-set-theme-light">
            <span>Light</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-dark">
            <span>Dark</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-auto">
            <span>Automatic</span>
          </a>
        </div>
      </li>
      

      

    </ul>

  </div>
</nav>


  <article class="article">

  




















  
  
    
  


<div class="article-container pt-3">
  <h1>Applying sentiment analysis on IATF resolutions</h1>

  
  <p class="page-subtitle">Steps in performing sentiment analysis using R</p>
  

  


<div class="article-metadata">

  
  
  
  
  <div>
    

  
  <span ><a href="/author/ernest-guevarra/">Ernest Guevarra</a></span>
  </div>
  
  

  
  <span class="article-date">
    
    
      
          Last updated on
      
    
    Jun 18, 2020
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    12 min read
  </span>
  

  
  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder mr-1"></i><a href="/category/research/">Research</a>, <a href="/category/rstats/">rstats</a></span>
  

</div>

  













<div class="btn-links mb-3">
  
  








  









  
  <a class="btn btn-outline-primary my-1 mr-1" href="/project/topic-modelling/">
    Project
  </a>
  











</div>


</div>


<div class="article-header container featured-image-wrapper mt-4 mb-4" style="max-width: 1200px; max-height: 831px;">
  <div style="position: relative">
    <img src="/post/applying-sentiment-analysis/featured_hu773b29531086a7055cacaaf3fe15cb95_336341_1200x0_resize_lanczos_2.png" alt="" class="featured-image">
    <span class="article-header-caption">Image credit: CoMo Philippines</span>
  </div>
</div>



  <div class="article-container">

    <div class="article-style">
      
<script src="/rmarkdown-libs/htmlwidgets/htmlwidgets.js"></script>
<script src="/rmarkdown-libs/viz/viz.js"></script>
<link href="/rmarkdown-libs/DiagrammeR-styles/styles.css" rel="stylesheet" />
<script src="/rmarkdown-libs/grViz-binding/grViz.js"></script>


<p><strong>Sentiment analysis</strong> or <strong>opinion mining</strong> as it’s sometimes called is commonly used to assess affective states and subjective information such as opinion and attitudes of subjects of interest using language <a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>,<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>. The most common use case of sentiment analysis is on analysing product or service reviews that are made available on the internet but it is increasingly being used in research that aims to quantify public sentiment or opinion. In the advent of Web 2.0 and wide use of various social media platforms alongside much affordable access to increased computing power for most people, the use of sentiment analysis has increased and expanded to various fields such as stock and financial markets, elections, extreme events and disaster, medicine, and policy analysis <a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>.</p>
<p>Using the text data on IATF resolutions available from the <a href="https://como-ph.github.io/covidphtext">covidphtext</a> package we developed, we explore the use of <strong>sentiment analysis</strong> as one of several <em>natural language processing (NLP)</em>, <em>text analysis</em> and <em>computational linguistics</em> techniques we plan to use for assessing Philippine government policy with regard to the response to the COVID-19 pandemic. The following workflow illustrates the process we use:</p>
<div class="figure" style="text-align: center"><span id="fig:workflow"></span>
<div id="htmlwidget-1" style="width:576px;height:768px;" class="grViz html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"diagram":"\n  digraph sentimentAnalysis {\n\n    # a \"graph\" statement\n    graph [overlap = false, fontsize = 14, fontname = Helvetica]\n\n    # Terminal nodes\n    node [shape = oval, width = 1.5, penwidth = 1.5]\n        \n    a [label = \"Start\"];\n    g [label = \"End\"];\n\n    # Input/output nodes\n    node [shape = parallelogram, height = 1, width = 1.5, penwidth = 1.5]\n    \n    b [label = \"1. covidphtext\ntext data\"];\n    f [label = \"5. Visualise\"];\n\n    # Process nodes\n    node [shape = rect, fixedsize = true, height = 1, width = 1.5, penwidth = 1.5]\n  \n    c [label = \"2. Tokenise\ndata\"];\n    d [label = \"3. Apply\nsentiment\nlexicon\"];\n    e [label = \"4. Summarise\"];\n\n    edge [minlen = 2, arrowsize = 1.5, penwidth = 1.5]\n    \n    a -> b\n    b -> c\n    c -> d\n    c -> e\n    d -> e\n    e -> f\n    f -> g\n\n    subgraph {\n      rank = same; c; d;\n    }\n  }","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
<p class="caption">
Figure 1: Sentiment analysis workflow
</p>
</div>
<div id="step-1-text-data-covidphtext" class="section level2">
<h2>Step 1: Text data: covidphtext</h2>
<p>As described in an earlier <a href="https://como-ph.github.io/post/covidphtext/">post</a>, the <strong>covidphtext</strong> contains IATF resolutions text data structured for the purpose of text analysis. What we need to do now is to combine all resolutions into a single dataset. There is a convenience function in <strong>covidphtext</strong> that helps with this called <code>combine_iatf</code> and is used as follows:</p>
<pre class="r"><code>allText &lt;- covidphtext::combine_iatf(res = c(1:15, 17:46))</code></pre>
<p>You will notice that we left out <strong>IATF Resolution No. 16.</strong>. This resolution is the only resolution that has been written in Filipino (see below).</p>
<pre><code>## # A tibble: 87 x 7
##    linenumber text                       source type       id section date      
##         &lt;int&gt; &lt;chr&gt;                      &lt;chr&gt;  &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;date&gt;    
##  1          1 Inter-Agency Task Force f… IATF   resolu…    16 heading 2020-03-30
##  2          2 Additional Guidelines for… IATF   resolu…    16 heading 2020-03-30
##  3          3 March 30, 2020             IATF   resolu…    16 heading 2020-03-30
##  4          4 Resolution No. 16          IATF   resolu…    16 heading 2020-03-30
##  5          5 A. Ayon sa direktiba ng D… IATF   resolu…    16 operat… 2020-03-30
##  6          6 Autonomous Region in Musl… IATF   resolu…    16 operat… 2020-03-30
##  7          7 mga pasilidad na maaring … IATF   resolu…    16 operat… 2020-03-30
##  8          8 Inaatasan and DOT at iban… IATF   resolu…    16 operat… 2020-03-30
##  9          9 pagtukoy ng mga pasilidad… IATF   resolu…    16 operat… 2020-03-30
## 10         10 Ang mga natukoy na pasili… IATF   resolu…    16 operat… 2020-03-30
## # … with 77 more rows</code></pre>
<p>Whilst it is possible to perform multi-lingual sentiment analysis, there is still no reliable <strong>sentiment lexicon</strong> (see following section for definition) for Filipino. Leaving out <strong>IATF Resolution No. 16</strong>, we arrive at the following concatenated IATF resolutions</p>
<pre><code>## # A tibble: 5,774 x 7
##    linenumber text                       source type       id section date      
##         &lt;int&gt; &lt;chr&gt;                      &lt;chr&gt;  &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;date&gt;    
##  1          1 Republic of the Philippin… IATF   resolu…     1 heading 2020-01-28
##  2          2 Department of Health       IATF   resolu…     1 heading 2020-01-28
##  3          3 Office of the Secretary    IATF   resolu…     1 heading 2020-01-28
##  4          4 Inter-Agency Task Force f… IATF   resolu…     1 heading 2020-01-28
##  5          5 Emerging Infectious Disea… IATF   resolu…     1 heading 2020-01-28
##  6          6 28 January 2020            IATF   resolu…     1 heading 2020-01-28
##  7          7 Resolution No. 01          IATF   resolu…     1 heading 2020-01-28
##  8          8 Series of 2020             IATF   resolu…     1 heading 2020-01-28
##  9          9 Recommendations for the M… IATF   resolu…     1 heading 2020-01-28
## 10         10 Novel Coronavirus Situati… IATF   resolu…     1 &lt;NA&gt;    2020-01-28
## # … with 5,764 more rows</code></pre>
<p>with 7 columns and 5774 rows of text. We then consider whether all the sections of a resolution is going to be useful for sentiment analysis. A typical resolution is composed of 3 sections:</p>
<ul>
<li><p><strong>Heading</strong> - contains the <em>body proposing the resolution</em>, the <em>subject of the resolution</em>, the <em>resolution number</em> and the <em>date resolution is issued</em>;</p></li>
<li><p><strong>Preambulatory clauses</strong> - contains the <em>preamble statements of the resolution</em> i.e., the reasons for which the proposing body is addressing the issue and highlights past action done by the body or any other organisation regarding the issue. This is usually composed of a series of phrases that starts with the <strong>WHEREAS</strong></p></li>
<li><p><strong>Operative clauses</strong> - contains phrases/statements that offer solutions to the issues stated in the preamble.These phrases are action-oriented starting with a verb followed by the proposed solution. This section usually starts off with <strong>LET IT BE RESOLVED</strong></p></li>
</ul>
<p>The IATF Resolutions very much follow the aforementioned structure with the addition of a section stating the <strong>approval of the resolution and the signatories</strong> approving the resolution, and in later resolutions a section <strong>certifying</strong> that the resolution has been approved.</p>
<p>For purposes of sentiment analysis, the most meaningful sections to use will be the sections on preambulatory clauses and operative clauses. So, we further subset the concatenated text dataset of IATF Resolutions to only contain those that are preambulatory and operative clauses. You will notice that in the text data of each of the IATF Resolutions, these sections have been identified through the variable named <code>section</code>. We use this variable to filter the sections we need as follows:</p>
<pre class="r"><code>allText &lt;- allText %&gt;%
  filter(section %in% c(&quot;preamble&quot;, &quot;operative&quot;))</code></pre>
<p>which results in</p>
<pre><code>## # A tibble: 4,048 x 7
##    linenumber text                        source type      id section date      
##         &lt;int&gt; &lt;chr&gt;                       &lt;chr&gt;  &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;   &lt;date&gt;    
##  1         11 WHEREAS, Executive Order N… IATF   resol…     1 preamb… 2020-01-28
##  2         12 for the Management of Emer… IATF   resol…     1 preamb… 2020-01-28
##  3         13 WHEREAS, the Inter-agency … IATF   resol…     1 preamb… 2020-01-28
##  4         14 identify, screen, and assi… IATF   resol…     1 preamb… 2020-01-28
##  5         15 prevent and/or minimize th… IATF   resol…     1 preamb… 2020-01-28
##  6         16 as prevent and/or minimize… IATF   resol…     1 preamb… 2020-01-28
##  7         17 WHEREAS, on January 7, 202… IATF   resol…     1 preamb… 2020-01-28
##  8         18 the viral pneumonia outbre… IATF   resol…     1 preamb… 2020-01-28
##  9         19 (2019-nCoV) that has not b… IATF   resol…     1 preamb… 2020-01-28
## 10         20 WHEREAS, as of January 27,… IATF   resol…     1 preamb… 2020-01-28
## # … with 4,038 more rows</code></pre>
<p>We are now left with <code>4048</code> rows of text for sentiment analysis.</p>
<p>Finally, we perform some final data cleaning and processing that will be useful when performing sentiment analysis. We convert the word <strong>COVID-19</strong> to <strong>COVID19</strong> without the dash. Since this word will most likely be a critical word in this analysis, we wanted to ensure that we capture it in its entirety. The next step on <strong>tokenisation</strong> removes any punctuation used in the text including dashes and will treat <strong>COVID</strong> as a separate word from <strong>19</strong>. We remove the dash prior to tokenisation so that we can keep these two as one word.</p>
<pre class="r"><code>allText$text &lt;- str_replace_all(string = allText$text, 
                                pattern = &quot;COVID-19&quot;, 
                                replacement = &quot;COVID19&quot;)</code></pre>
<p>And then, anticipating that we will need some kind of grouping variable later in the analysis, we create a <code>month</code> variable within the concatenated text dataset that indicates the month when a specific resolution was issued. This was done as follows:</p>
<pre class="r"><code>allText &lt;- allText %&gt;%
  mutate(month = factor(x = months(date),
                        levels = c(&quot;January&quot;, &quot;February&quot;, &quot;March&quot;, 
                                   &quot;April&quot;, &quot;May&quot;, &quot;June&quot;)))</code></pre>
<p>Our final working text dataset is this:</p>
<pre><code>## # A tibble: 4,048 x 8
##    linenumber text                  source type      id section date       month
##         &lt;int&gt; &lt;chr&gt;                 &lt;chr&gt;  &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;   &lt;date&gt;     &lt;fct&gt;
##  1         11 WHEREAS, Executive O… IATF   resol…     1 preamb… 2020-01-28 Janu…
##  2         12 for the Management o… IATF   resol…     1 preamb… 2020-01-28 Janu…
##  3         13 WHEREAS, the Inter-a… IATF   resol…     1 preamb… 2020-01-28 Janu…
##  4         14 identify, screen, an… IATF   resol…     1 preamb… 2020-01-28 Janu…
##  5         15 prevent and/or minim… IATF   resol…     1 preamb… 2020-01-28 Janu…
##  6         16 as prevent and/or mi… IATF   resol…     1 preamb… 2020-01-28 Janu…
##  7         17 WHEREAS, on January … IATF   resol…     1 preamb… 2020-01-28 Janu…
##  8         18 the viral pneumonia … IATF   resol…     1 preamb… 2020-01-28 Janu…
##  9         19 (2019-nCoV) that has… IATF   resol…     1 preamb… 2020-01-28 Janu…
## 10         20 WHEREAS, as of Janua… IATF   resol…     1 preamb… 2020-01-28 Janu…
## # … with 4,038 more rows</code></pre>
</div>
<div id="step-2-tokenise-data" class="section level2">
<h2>Step 2: Tokenise data</h2>
<p>We are now ready to <strong>tokenise</strong> the data. <strong>Tokenisation</strong> of text data simply means structuring the text data into <strong>tokens</strong> – meaningful units of text such as a word, or groups of words, or a sentence, or a paragraph. For sentiment analysis, the most useful token will be a word mainly because the <strong>sentiment lexicons</strong> (see following section for definition) we plan to use are based on words.</p>
<p>We use the <a href="https://juliasilge.github.io/tidytext/">tidytext</a> package and the function <code>unnest_tokens</code> within it to perform <strong>tokenisation</strong> using words as follows:</p>
<pre class="r"><code>tidy_resolutions &lt;- allText %&gt;%
  unnest_tokens(output = word, input = text)</code></pre>
<p>This results in the following dataset:</p>
<pre><code>## # A tibble: 40,024 x 8
##    linenumber source type          id section  date       month   word     
##         &lt;int&gt; &lt;chr&gt;  &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;    &lt;date&gt;     &lt;fct&gt;   &lt;chr&gt;    
##  1         11 IATF   resolution     1 preamble 2020-01-28 January whereas  
##  2         11 IATF   resolution     1 preamble 2020-01-28 January executive
##  3         11 IATF   resolution     1 preamble 2020-01-28 January order    
##  4         11 IATF   resolution     1 preamble 2020-01-28 January no       
##  5         11 IATF   resolution     1 preamble 2020-01-28 January 168      
##  6         11 IATF   resolution     1 preamble 2020-01-28 January s        
##  7         11 IATF   resolution     1 preamble 2020-01-28 January 2014     
##  8         11 IATF   resolution     1 preamble 2020-01-28 January creates  
##  9         11 IATF   resolution     1 preamble 2020-01-28 January the      
## 10         11 IATF   resolution     1 preamble 2020-01-28 January inter    
## # … with 40,014 more rows</code></pre>
<p>You will notice that our new tokenised dataset is structured such that each word in the concatenated IATF Resolutions of preambles and operative clauses is a unit of data i.e. in a row. We now have a dataset with <code>40024</code> rows and <code>8</code> columns that we can use for the next step.</p>
</div>
<div id="step-3-apply-sentiment-lexicon" class="section level2">
<h2>Step 3: Apply sentiment lexicon</h2>
<p>We now apply a <strong>sentiment lexicon</strong> onto the tokenised dataset from the previous step. <strong>Sentiment lexicons</strong> are basically a list of common words in a specific language with each word having a value pertaining to the sentiment or emotion associated with a specific word. The value assigned to a word can be binary i.e. negative or positive, or can be categories of sentiments or emotions such as positive, negative, anger, anticipation, disgust, fear, joy, sadness, surprise, and trust, or a numerical value on a scale that runs from negative values indicating progressively negative sentiments to positive values indicating progressively positive sentiments.</p>
<p>The <a href="https://juliasilge.github.io/tidytext/">tidytext</a> package comes with three general use lexicons:</p>
<ul>
<li><p><code>AFINN</code> - from Finn Årup Nielsen which is a lexicon that assigns a score to words from -5 to +5 with negative scores indicating negative sentiments and positive scores indicating positive sentiments;</p></li>
<li><p><code>bing</code> - from Bing Liu and collaborators which is a lexicon that simply classifies words into either negative or positive categories; and,</p></li>
<li><p><code>nrc</code> - from Saif Mohammad and Peter Turney which is a lexicon that groups words into categories of positive, negative, anger, anticipation, disgust, fear, joy, sadness, surprise, or trust</p></li>
</ul>
<p>We apply the sentiment lexicon from Bing and colleagues to our tokenised data as follows:</p>
<pre class="r"><code>resolution_sentiment &lt;- tidy_resolutions %&gt;%
  inner_join(get_sentiments(&quot;bing&quot;))</code></pre>
<p>What we are basically doing here is to match the words in our tokenised data with the words in the sentiment lexicion from Bing and colleagues to get the sentiment value of positive or negative for our tokenised data. This results in the following:</p>
<pre><code>## # A tibble: 1,303 x 9
##    linenumber source type       id section  date       month  word     sentiment
##         &lt;int&gt; &lt;chr&gt;  &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;    &lt;date&gt;     &lt;fct&gt;  &lt;chr&gt;    &lt;chr&gt;    
##  1         14 IATF   resolu…     1 preamble 2020-01-28 Janua… infected negative 
##  2         15 IATF   resolu…     1 preamble 2020-01-28 Janua… well     positive 
##  3         18 IATF   resolu…     1 preamble 2020-01-28 Janua… outbreak negative 
##  4         21 IATF   resolu…     1 preamble 2020-01-28 Janua… risk     negative 
##  5         21 IATF   resolu…     1 preamble 2020-01-28 Janua… infecti… negative 
##  6         25 IATF   resolu…     1 operati… 2020-01-28 Janua… recomme… positive 
##  7         26 IATF   resolu…     1 operati… 2020-01-28 Janua… support  positive 
##  8         26 IATF   resolu…     1 operati… 2020-01-28 Janua… accurate positive 
##  9         27 IATF   resolu…     1 operati… 2020-01-28 Janua… timely   positive 
## 10         27 IATF   resolu…     1 operati… 2020-01-28 Janua… support  positive 
## # … with 1,293 more rows</code></pre>
<div class="figure" style="text-align: center"><span id="fig:sentiment1"></span>
<img src="/post/sentiment-analysis/index_files/figure-html/sentiment1-1.png" alt="Sentiment analysis of IATF resolutions" width="1152" />
<p class="caption">
Figure 2: Sentiment analysis of IATF resolutions
</p>
</div>
<p>The resolutions over time generally starts off on a positive note (except for resolution 14 on 20 March 2020 and resolution 15 on 25 March 2020).</p>
<p>Early on in the pandemic, in the first two weeks of March 2020 (resolutions up to 17 March 2020), the resolutions generally starts off on a mildly positive note but almost immediately gets to a more negative sentiment as the resolution progresses to the end. This is particularly evident in the first two resolution in the first week of March. By the second week of March, some small spikes of positivity is noted towards the end of the resolutions but still with a more negative tone at the end.</p>
<p>By the second week of March 2020 up to early April 2020, there is a shift to a mostly more positive sentiment to the resolutions right from the start. A few sharp troughs of negativity on the 25th of March and the 3rd of April 2020 can be noted.</p>
<div class="figure" style="text-align: center"><span id="fig:sentiment2a"></span>
<img src="/post/sentiment-analysis/index_files/figure-html/sentiment2a-1.png" alt="Words that contribute to positive and negative sentiment in the IATF resolutions" width="768" />
<p class="caption">
Figure 3: Words that contribute to positive and negative sentiment in the IATF resolutions
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:sentiment2b"></span>
<img src="/post/sentiment-analysis/index_files/figure-html/sentiment2b-1.png" alt="Average sentiment value for IATF resolutions by month" width="768" />
<p class="caption">
Figure 4: Average sentiment value for IATF resolutions by month
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:sentiment2c"></span>
<img src="/post/sentiment-analysis/index_files/figure-html/sentiment2c-1.png" alt="Sentiment value across all resolutions by month" width="1152" />
<p class="caption">
Figure 5: Sentiment value across all resolutions by month
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:sentiment3"></span>
<img src="/post/sentiment-analysis/index_files/figure-html/sentiment3-1.png" alt="The most common words in the IATF resolutions" width="100%" />
<p class="caption">
Figure 6: The most common words in the IATF resolutions
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:sentiment4"></span>
<img src="/post/sentiment-analysis/index_files/figure-html/sentiment4-1.png" alt="Most common positive and negative word in the IATF resolutions" width="100%" />
<p class="caption">
Figure 7: Most common positive and negative word in the IATF resolutions
</p>
</div>
<p><br>
<br></p>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Mäntylä MV, Graziotin D, Kuutila M. The evolution of sentiment analysis—A review of research topics, venues, and top cited papers. Computer Science Review. 2018;27: 16–32. <a href="doi:10.1016/j.cosrev.2017.10.002" class="uri">doi:10.1016/j.cosrev.2017.10.002</a><a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Liu B. Handbook Chapter: Sentiment Analysis and Subjectivity. Handbook of Natural Language Processing, Handbook of Natural Language Processing, Marcel Dekker, Inc. New York, NY, USA (2009)<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>Mäntylä MV, Graziotin D, Kuutila M. The evolution of sentiment analysis—A review of research topics, venues, and top cited papers. Computer Science Review. 2018;27: 16–32. <a href="doi:10.1016/j.cosrev.2017.10.002" class="uri">doi:10.1016/j.cosrev.2017.10.002</a><a href="#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

    </div>

    






<div class="article-tags">
  
  <a class="badge badge-light" href="/tag/iatf/">IATF</a>
  
  <a class="badge badge-light" href="/tag/sentiment-analysis/">sentiment analysis</a>
  
</div>



<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/post/applying-sentiment-analysis/&amp;text=Applying%20sentiment%20analysis%20on%20IATF%20resolutions" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/post/applying-sentiment-analysis/&amp;t=Applying%20sentiment%20analysis%20on%20IATF%20resolutions" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Applying%20sentiment%20analysis%20on%20IATF%20resolutions&amp;body=/post/applying-sentiment-analysis/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/post/applying-sentiment-analysis/&amp;title=Applying%20sentiment%20analysis%20on%20IATF%20resolutions" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="whatsapp://send?text=Applying%20sentiment%20analysis%20on%20IATF%20resolutions%20/post/applying-sentiment-analysis/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/post/applying-sentiment-analysis/&amp;title=Applying%20sentiment%20analysis%20on%20IATF%20resolutions" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>












  
    
    





  
    
    
    
    
    
    <div class="media author-card content-widget-hr">
      
        
        <img class="avatar mr-3 avatar-circle" src="/author/ernest-guevarra/avatar_hu4f9a547149ed73977cb3e5de1c9e7ab2_7097_270x270_fill_q90_lanczos_center.jpeg" alt="Ernest Guevarra">
      

      <div class="media-body">
        <h5 class="card-title"><a href="/author/ernest-guevarra/">Ernest Guevarra</a></h5>
        <h6 class="card-subtitle">Advisor</h6>
        <p class="card-text">Public health specialist, spatial epidemiologist, R developer</p>
        <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="/#contact" >
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://www.linkedin.com/in/ernestguevarra" target="_blank" rel="noopener">
        <i class="fab fa-linkedin"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://scholar.google.com/citations?user=U9scwmIAAAAJ&amp;hl=en" target="_blank" rel="noopener">
        <i class="ai ai-google-scholar"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://github.com/ernestguevarra" target="_blank" rel="noopener">
        <i class="fab fa-github"></i>
      </a>
    </li>
  
</ul>

      </div>
    </div>
  


  












  
  
  <div class="article-widget content-widget-hr">
    <h3>Related</h3>
    <ul>
      
      <li><a href="/post/creating-text-data-from-iatf-resolutions/">Creating text data from IATF resolutions for use in text analysis</a></li>
      
    </ul>
  </div>
  





  </div>
</article>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.4.8/mermaid.min.js" integrity="sha256-lyWCDMnMeZiXRi7Zl54sZGKYmgQs4izcT7+tKc+KUBk=" crossorigin="anonymous" title="mermaid"></script>
      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js" integrity="sha256-eOgo0OtLL4cdq7RdwRUiGKLX9XsIJ7nGhWEKbohmVAQ=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/r.min.js"></script>
        
      

    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js" integrity="sha256-EErZamuLefUnbMBQbsEqu1USa+btR2oIlCpBJbyD4/g=" crossorigin="anonymous"></script>
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    <script>const isSiteThemeDark = false;</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks",
        'slides' : "Slides"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.37431be2d92d7fb0160054761ab79602.js"></script>

    






  
  
  <div class="container">
    <footer class="site-footer">
  
  <p class="powered-by">
    
      <a href="/privacy/">Privacy Policy</a>
    
    
       &middot; 
      <a href="/terms/">Terms</a>
    
  </p>
  

  <p class="powered-by">
    © CoMo Philippines 2020
  </p>

  
  





  
  
  
  

  
  
    
  
  
    
  

  

  
  <p class="powered-by copyright-license-text">
    This work is licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0" rel="noopener noreferrer" target="_blank">CC BY NC ND 4.0</a>
  </p>
  

  <p class="powered-by footer-license-icons">
    <a href="https://creativecommons.org/licenses/by-nc-nd/4.0" rel="noopener noreferrer" target="_blank">
      <img src="https://search.creativecommons.org/static/img/cc_icon.svg" alt="CC icon">
      <img src="https://search.creativecommons.org/static/img/cc-by_icon.svg" alt="CC by icon">
      
        <img src="https://search.creativecommons.org/static/img/cc-nc_icon.svg" alt="CC NC icon">
      
      
        <img src="https://search.creativecommons.org/static/img/cc-nd_icon.svg" alt="CC ND icon">
      
    </a>
  </p>




  <p class="powered-by">
    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" class="back-to-top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
